<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>工资单 - Payslip</title>
</head>
<body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; margin: 0; padding: 0;">
    <div style="max-width: 600px; margin: 0 auto; padding: 20px;">
        @if(isset($customMessage) && !empty($customMessage))
            {!! nl2br(e($customMessage)) !!}
        @else
            <p>尊敬的 {{ $payroll->user->name }}，</p>
            
            <p>您的 {{ $payroll->year }}年{{ $payroll->month }}月工资单已生成并标记为已发放，请查看附件中的PDF文件获取详细信息。</p>
            
            @if($payroll->user->company)
                <p><strong>公司 / Company:</strong> {{ $payroll->user->company->name }}</p>
            @endif
            
            <p>如有任何疑问，请联系人力资源部门。</p>
        @endif
        
        <p style="color: #7f8c8d; font-size: 12px; margin-top: 30px;">
            此邮件由系统自动发送，请勿回复。<br>
            This email is automatically generated by the system, please do not reply.
        </p>
    </div>
</body>
</html>

